# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 06:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2016, 4, 1, 6, 1, 28, 766002, tzinfo=utc), verbose_name='date registered')),
                ('take_out_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='time taken out')),
                ('take_out_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['register_date'],
            },
        ),
    ]
