# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('physicsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
    ]
