# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-01 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsdb', '0002_auto_20160401_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(default='No Name', max_length=128),
            preserve_default=False,
        ),
    ]
