# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['register_date']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room_number',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='shelf_label',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='take_out_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='time taken out'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='take_out_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
