# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20160610_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='subject',
            field=models.CharField(default=datetime.datetime(2016, 6, 13, 5, 15, 5, 244515, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
    ]
